# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.1
        with:
          node-version: "14"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install

      - name: Build webapp
        run: yarn run build

      - name: Deploy to beta web server
        uses: marcodallasanta/ssh-scp-deploy@v1.0.5
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          user: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          local: "build/*"
          remote: "~/webroot-beta/"
          pre_upload: rm -r ~/webroot-beta/*
