# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.1
        with:
          node-version: "14"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install

      - name: Run eslint
        run: yarn run lint

      - name: Force version in package.json to match Git tag
        if: ${{ github.ref_type == 'tag' }}
        run: |
          sed -i -e "s/\(version\": \"\)[0-9\.]*/\1${{github.ref_name}}/" package.json

      - name: Append build metadata to package.json version field
        run: |
          sed -i -e "s/\(version\": \"[0-9\.]*\)-dev/\1+`echo ${{github.sha}} | cut -c1-7`/" package.json

      - name: Build webapp
        run: yarn run build

      - name: Run tests
        run: yarn run test

# # Disabled on migration to netlify:
#      - name: Deploy to beta web server
#        uses: jamesremuscat/ssh-scp-deploy@main
#        with:
#          host: ${{ secrets.SSH_HOST }}
#          port: ${{ secrets.SSH_PORT }}
#          user: ${{ secrets.SSH_USERNAME }}
#          key: ${{ secrets.SSH_PRIVATE_KEY }}
#          local: "build/*"
#          remote: "~/webroot-beta/"
#          pre_upload: rm -r ~/webroot-beta/*
#          scp_options: "-l 2000"
