name: Update T71 packages

on:
  workflow_dispatch:
  registry_package:
    types: [published]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js environment
        uses: actions/setup-node@v3
        with:
          always-auth: true
          node-version: 18
          cache: "yarn"

      - name: Set up token for private package access
        env:
          GH_PACKAGES_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}
        run: |
          echo "@timing71:registry=https://npm.pkg.github.com" > .npmrc
          echo "//npm.pkg.github.com/:_authToken=${GH_PACKAGES_TOKEN}" >> .npmrc
          echo "always-auth=true" >> .npmrc

      - name: Update Timing71 packages
        uses: romoh/dependencies-autoupdate@v1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          update-command: "'yarn upgrade @timing71/common @timing71/services'"
          pr-branch: "master"
